version: "3.1"

services:
  api:
    build: 
      context: .
      target: dev
    volumes:
      - .:/app
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - DB_PORT=5432
      - DB_HOST=database
      - DB_USER=training_api
      - DB_PASSWORD=training_api
      - DB_NAME=training_api
    ports: 
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: training_api
      POSTGRES_PASSWORD: training_api
      POSTGRES_DB: training_api
    volumes:
      - ./tmp/postgressql:/var/lib/postgresql
    ports:
      - 5432:5432
    
    